version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8080"
    depends_on:
      - postgres
      - localstack
    environment:
      - PROFILE=integration-tests-docker
    restart: "no"
  postgres:
    image: postgres:14.1-alpine
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 20
    ports:
      - "1334:5432"
    env_file:
      - ./environment/integration/.env
  localstack:
    image: localstack/localstack:0.14.3
    restart: "no"
    environment:
      - SERVICES=s3
      - EAGER_SERVICE_LOADING=true
    ports:
      - "4568:4566"
