# Compile stage
FROM golang:1.18 AS build-env

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ADD . /dockerdev
WORKDIR /dockerdev

# Compile the application with the optimizations turned off
# This is important for the debugger to correctly work with the binary

RUN go build -gcflags "all=-N -l" -o /subscriptions ./src/main.go

# Final stage
FROM debian:buster

EXPOSE 8080 40000

WORKDIR /app
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /subscriptions /app/subscriptions
COPY --from=build-env /dockerdev/profiles /app/profiles
COPY --from=build-env /dockerdev/database/migrations /app/database/migrations
COPY --from=build-env /dockerdev/database/seed.sql /app/database/seed.sql

RUN mkdir -p "/tmp/dayfiles"

CMD ["/dlv", "--listen=:40000", "--headless=true", "--continue=true", "--api-version=2", "--accept-multiclient", "exec", "./subscriptions"]
