version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8080"
    depends_on:
      - postgres
    environment:
      - PROFILE=integration-tests-docker
    restart: "no"
  postgres:
    image: postgres:14.1-alpine
    restart: "no"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 20
    ports:
      - "1334:5432"
    env_file:
      - ./environment/integration/.env
