basePath: /
consumes:
- application/json
definitions:
  FooBarRequest:
    properties:
      bar:
        items:
          format: int64
          type: integer
        type: array
        x-go-name: Bar
      foo:
        type: string
        x-go-name: Foo
    title: FooBarRequest represents body of FooBar request.
    type: object
    x-go-package: github.com/pdrum/swagger-automation/api
  FooBarResponse:
    properties:
      baz:
        properties:
          prop:
            type: string
            x-go-name: Prop
        type: object
        x-go-name: Baz
    title: FooBarResponse represents body of FooBar response.
    type: object
    x-go-package: github.com/pdrum/swagger-automation/api
  GenericResponse:
    properties:
      details:
        type: string
        x-go-name: Details
    type: object
    x-go-package: subscriptions/src/models
  Healthcheck:
    properties:
      details:
        type: string
        x-go-name: Details
      up:
        type: boolean
        x-go-name: Up
    type: object
    x-go-package: subscriptions/src/models
  SubscriptionAction:
    properties:
      description:
        type: string
        x-go-name: Description
      name:
        type: string
        x-go-name: Name
      unit:
        type: string
        x-go-name: Unit
    type: object
    x-go-package: subscriptions/src/models
  SubscriptionActionList:
    properties:
      actions:
        items:
          $ref: '#/definitions/SubscriptionAction'
        type: array
        x-go-name: Actions
    type: object
    x-go-package: subscriptions/src/models
  SubscriptionResponse:
    properties:
      active:
        type: boolean
        x-go-name: Active
      subscriptionId:
        type: string
        x-go-name: SubscriptionId
    type: object
    x-go-package: subscriptions/src/models
  SubscriptionType:
    properties:
      id:
        format: int64
        type: integer
        x-go-name: ID
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: subscriptions/src/models
  SubscriptionTypeList:
    properties:
      subscriptions:
        items:
          $ref: '#/definitions/SubscriptionType'
        type: array
        x-go-name: Subscriptions
    type: object
    x-go-package: subscriptions/src/models
host: some-url-update.com
info:
  description: Documentation of our awesome Subscription API.
  title: Subscription Service.
  version: 1.0.0
paths:
  /deactivate/{id}:
    post:
      description: Log actions with API
      operationId: deactivateSubscriptionEndpoint
      parameters:
      - description: Request containing information about product to add
        in: body
        name: Body
        schema:
          type: string
      responses:
        "200":
          $ref: '#/responses/ProductResponse'
      tags:
      - deactivate-subscription
  /foobar:
    post:
      operationId: idOfFoobarEndpoint
      parameters:
      - description: This text will appear as description of your request body.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/FooBarRequest'
      responses:
        "200":
          $ref: '#/responses/foobarResponse'
      summary: Foobar does some amazing stuff.
      tags:
      - foobar-tag
  /healthcheck:
    get:
      description: Application Healthcheck. Checking database connection and used
        by readiness probe
      operationId: healthcheckEndpoint
      responses:
        "200":
          $ref: '#/responses/Healthcheck'
      tags:
      - application-healthcheck
  /liveness:
    get:
      description: Application Liveness. Checking the application is responsive. Used
        by the liveness probe
      operationId: livenessEndpoint
      responses:
        "200":
          $ref: '#/responses/Healthcheck'
      tags:
      - application-liveness
  /subscription-actions:
    get:
      operationId: subscriptionActionsEndpoint
      responses:
        "200":
          description: SubscriptionActionList
          schema:
            $ref: '#/definitions/SubscriptionActionList'
      summary: List the action types for subscriptions.
      tags:
      - subscription-actions
  /subscription-types:
    get:
      operationId: subscriptionTypesEndpoint
      responses:
        "200":
          description: SubscriptionTypeList
          schema:
            $ref: '#/definitions/SubscriptionTypeList'
      summary: List the type of subscriptions.
      tags:
      - subscription-types
  /subscription/{accountID}:
    get:
      description: Get or create subscription
      operationId: getOrCreateSubscriptionEndpoint
      responses:
        "200":
          $ref: '#/responses/models.SubscriptionResponse'
produces:
- application/json
responses:
  Healthcheck:
    description: Healthcheck Response containing status information.
    schema:
      $ref: '#/definitions/Healthcheck'
  Liveness:
    description: Liveness Response containing status information.
    schema:
      $ref: '#/definitions/Healthcheck'
  ProductResponse:
    description: Response containing details about product addition.
    schema:
      $ref: '#/definitions/GenericResponse'
  foobarResponse:
    description: This text will appear as description of your response body.
    schema:
      $ref: '#/definitions/FooBarResponse'
  getSubscriptionResponsesWrapper:
    description: Response for evaluate subscriptions
    schema:
      $ref: '#/definitions/SubscriptionResponse'
  subscriptionTypes:
    description: List of subscription actions.
    schema:
      $ref: '#/definitions/SubscriptionActionList'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
