openapi: 3.0.0
info:
  version: 1.0.0
  title: Subscriptions Service
  description: A service that deals with access to the KL platform
paths:
  /healthcheck:
    get:
      description: Returns whether the application is healthy (connected to dependencies)
      responses:
        "200":
          $ref: '#/components/responses/ApplicationStateResponse'
  /liveness:
    get:
      description: Returns whether the application is running
      responses:
        "200":
          $ref: '#/components/responses/ApplicationStateResponse'
  /test/{id}:
    post:
      description: This is a test endpoint
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of something or other
      requestBody:
          $ref: '#/components/requestBodies/TestRequest'
      responses:
        "200":
          $ref: '#/components/responses/ApplicationStateResponse'
components:
  responses:
    ApplicationStateResponse:
      description: Successful healthcheck or liveness response
      content:
        application/json:
          schema:
            type: object
            required:
              - up
              - details
            properties:
              up:
                type: boolean
              details:
                type: string
  requestBodies:
    TestRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - propertyA
            properties:
              propertyA:
                type: string
