apiVersion: apps/v1
kind: Deployment
metadata:
  name: athena-mock
  labels:
    app: athena-mock
spec:
  selector:
    matchLabels:
      app: athena-mock
  template:
    metadata:
      labels:
        app: athena-mock
    spec:
      containers:
        - name: athena-mock
          image: athena-mock
          ports:
            - containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: athena-mock
  name: athena-mock
  namespace: subscriptions
spec:
  ports:
    - name: "4567"
      port: 4567
      targetPort: 4567
  selector:
    app: athena-mock
status:
  loadBalancer: {}
