docker_build('local-go-image', '../../.',
    dockerfile='../../Dockerfile-debug',
    )

docker_build('athena-mock', '../../athena-mock', dockerfile='../../athena-mock/Dockerfile',)

k8s_yaml('go.yaml')
k8s_yaml('postgres.yaml')
k8s_yaml('athena.yaml')
k8s_resource('go-app', labels=['subscriptions'], port_forwards=['8020:8080', '40002:40000'], resource_deps=['postgres'])
k8s_resource('postgres', labels=['subscriptions'], port_forwards=1334)

k8s_yaml('localstack.yaml')
k8s_resource('localstack', labels=['localstack'], port_forwards=['4568:4566'])
