name: subscriptions service
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'
    - name: Run unit tests
      run: go test -v ./test/unit/...
    - name: Run integration tests
      run: ./run-integration-tests.sh
  build-push-docker-image:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push docker image
      run: echo test123

